package sample.entity;
// Generated Nov 22, 2014 5:12:09 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Serializable userId;
     private Serializable username;
     private Serializable password;
     private Serializable roles;
     private Serializable firstname;
     private Serializable middlename;
     private Serializable lastname;
     private Serializable email;
     private Serializable address;
     private Serializable phone;
     private Serializable avartar;
     private boolean isAble;
     private Set orders = new HashSet(0);
     private Set borrowsForAccepter = new HashSet(0);
     private Set borrowsForBorrower = new HashSet(0);

    public Account() {
    }

	
    public Account(Serializable userId, Serializable username, Serializable password, Serializable roles, Serializable firstname, Serializable lastname, Serializable email, Serializable address, Serializable phone, Serializable avartar, boolean isAble) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.roles = roles;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.address = address;
        this.phone = phone;
        this.avartar = avartar;
        this.isAble = isAble;
    }
    public Account(Serializable userId, Serializable username, Serializable password, Serializable roles, Serializable firstname, Serializable middlename, Serializable lastname, Serializable email, Serializable address, Serializable phone, Serializable avartar, boolean isAble, Set orders, Set borrowsForAccepter, Set borrowsForBorrower) {
       this.userId = userId;
       this.username = username;
       this.password = password;
       this.roles = roles;
       this.firstname = firstname;
       this.middlename = middlename;
       this.lastname = lastname;
       this.email = email;
       this.address = address;
       this.phone = phone;
       this.avartar = avartar;
       this.isAble = isAble;
       this.orders = orders;
       this.borrowsForAccepter = borrowsForAccepter;
       this.borrowsForBorrower = borrowsForBorrower;
    }
   
    public Serializable getUserId() {
        return this.userId;
    }
    
    public void setUserId(Serializable userId) {
        this.userId = userId;
    }
    public Serializable getUsername() {
        return this.username;
    }
    
    public void setUsername(Serializable username) {
        this.username = username;
    }
    public Serializable getPassword() {
        return this.password;
    }
    
    public void setPassword(Serializable password) {
        this.password = password;
    }
    public Serializable getRoles() {
        return this.roles;
    }
    
    public void setRoles(Serializable roles) {
        this.roles = roles;
    }
    public Serializable getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(Serializable firstname) {
        this.firstname = firstname;
    }
    public Serializable getMiddlename() {
        return this.middlename;
    }
    
    public void setMiddlename(Serializable middlename) {
        this.middlename = middlename;
    }
    public Serializable getLastname() {
        return this.lastname;
    }
    
    public void setLastname(Serializable lastname) {
        this.lastname = lastname;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public Serializable getPhone() {
        return this.phone;
    }
    
    public void setPhone(Serializable phone) {
        this.phone = phone;
    }
    public Serializable getAvartar() {
        return this.avartar;
    }
    
    public void setAvartar(Serializable avartar) {
        this.avartar = avartar;
    }
    public boolean isIsAble() {
        return this.isAble;
    }
    
    public void setIsAble(boolean isAble) {
        this.isAble = isAble;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }
    public Set getBorrowsForAccepter() {
        return this.borrowsForAccepter;
    }
    
    public void setBorrowsForAccepter(Set borrowsForAccepter) {
        this.borrowsForAccepter = borrowsForAccepter;
    }
    public Set getBorrowsForBorrower() {
        return this.borrowsForBorrower;
    }
    
    public void setBorrowsForBorrower(Set borrowsForBorrower) {
        this.borrowsForBorrower = borrowsForBorrower;
    }




}


