package sample.entity;
// Generated Nov 22, 2014 5:12:09 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private int authorId;
     private Serializable firstname;
     private Serializable middlename;
     private Serializable lastname;
     private Serializable image;
     private Serializable about;
     private int borrowTimes;
     private int orderTimes;
     private Set books = new HashSet(0);

    public Author() {
    }

	
    public Author(int authorId, Serializable firstname, Serializable middlename, Serializable lastname, int borrowTimes, int orderTimes) {
        this.authorId = authorId;
        this.firstname = firstname;
        this.middlename = middlename;
        this.lastname = lastname;
        this.borrowTimes = borrowTimes;
        this.orderTimes = orderTimes;
    }
    public Author(int authorId, Serializable firstname, Serializable middlename, Serializable lastname, Serializable image, Serializable about, int borrowTimes, int orderTimes, Set books) {
       this.authorId = authorId;
       this.firstname = firstname;
       this.middlename = middlename;
       this.lastname = lastname;
       this.image = image;
       this.about = about;
       this.borrowTimes = borrowTimes;
       this.orderTimes = orderTimes;
       this.books = books;
    }
   
    public int getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(int authorId) {
        this.authorId = authorId;
    }
    public Serializable getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(Serializable firstname) {
        this.firstname = firstname;
    }
    public Serializable getMiddlename() {
        return this.middlename;
    }
    
    public void setMiddlename(Serializable middlename) {
        this.middlename = middlename;
    }
    public Serializable getLastname() {
        return this.lastname;
    }
    
    public void setLastname(Serializable lastname) {
        this.lastname = lastname;
    }
    public Serializable getImage() {
        return this.image;
    }
    
    public void setImage(Serializable image) {
        this.image = image;
    }
    public Serializable getAbout() {
        return this.about;
    }
    
    public void setAbout(Serializable about) {
        this.about = about;
    }
    public int getBorrowTimes() {
        return this.borrowTimes;
    }
    
    public void setBorrowTimes(int borrowTimes) {
        this.borrowTimes = borrowTimes;
    }
    public int getOrderTimes() {
        return this.orderTimes;
    }
    
    public void setOrderTimes(int orderTimes) {
        this.orderTimes = orderTimes;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


