package sample.entity;
// Generated Nov 22, 2014 5:12:09 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Serializable isbn;
     private Publisher publisher;
     private Serializable title;
     private Serializable author;
     private Date publishYear;
     private Serializable image;
     private Serializable about;
     private double price;
     private int dueTime;
     private boolean isAble;
     private int numOfCopy;
     private int copiesAvailable;
     private int borrowTimes;
     private int orderTimes;
     private Set tags = new HashSet(0);
     private Set orders = new HashSet(0);
     private Set copies = new HashSet(0);
     private Set authors = new HashSet(0);

    public Book() {
    }

	
    public Book(Serializable isbn, Publisher publisher, Serializable title, Date publishYear, double price, int dueTime, boolean isAble, int numOfCopy, int copiesAvailable, int borrowTimes, int orderTimes) {
        this.isbn = isbn;
        this.publisher = publisher;
        this.title = title;
        this.publishYear = publishYear;
        this.price = price;
        this.dueTime = dueTime;
        this.isAble = isAble;
        this.numOfCopy = numOfCopy;
        this.copiesAvailable = copiesAvailable;
        this.borrowTimes = borrowTimes;
        this.orderTimes = orderTimes;
    }
    public Book(Serializable isbn, Publisher publisher, Serializable title, Serializable author, Date publishYear, Serializable image, Serializable about, double price, int dueTime, boolean isAble, int numOfCopy, int copiesAvailable, int borrowTimes, int orderTimes, Set tags, Set orders, Set copies, Set authors) {
       this.isbn = isbn;
       this.publisher = publisher;
       this.title = title;
       this.author = author;
       this.publishYear = publishYear;
       this.image = image;
       this.about = about;
       this.price = price;
       this.dueTime = dueTime;
       this.isAble = isAble;
       this.numOfCopy = numOfCopy;
       this.copiesAvailable = copiesAvailable;
       this.borrowTimes = borrowTimes;
       this.orderTimes = orderTimes;
       this.tags = tags;
       this.orders = orders;
       this.copies = copies;
       this.authors = authors;
    }
   
    public Serializable getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(Serializable isbn) {
        this.isbn = isbn;
    }
    public Publisher getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }
    public Serializable getTitle() {
        return this.title;
    }
    
    public void setTitle(Serializable title) {
        this.title = title;
    }
    public Serializable getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Serializable author) {
        this.author = author;
    }
    public Date getPublishYear() {
        return this.publishYear;
    }
    
    public void setPublishYear(Date publishYear) {
        this.publishYear = publishYear;
    }
    public Serializable getImage() {
        return this.image;
    }
    
    public void setImage(Serializable image) {
        this.image = image;
    }
    public Serializable getAbout() {
        return this.about;
    }
    
    public void setAbout(Serializable about) {
        this.about = about;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getDueTime() {
        return this.dueTime;
    }
    
    public void setDueTime(int dueTime) {
        this.dueTime = dueTime;
    }
    public boolean isIsAble() {
        return this.isAble;
    }
    
    public void setIsAble(boolean isAble) {
        this.isAble = isAble;
    }
    public int getNumOfCopy() {
        return this.numOfCopy;
    }
    
    public void setNumOfCopy(int numOfCopy) {
        this.numOfCopy = numOfCopy;
    }
    public int getCopiesAvailable() {
        return this.copiesAvailable;
    }
    
    public void setCopiesAvailable(int copiesAvailable) {
        this.copiesAvailable = copiesAvailable;
    }
    public int getBorrowTimes() {
        return this.borrowTimes;
    }
    
    public void setBorrowTimes(int borrowTimes) {
        this.borrowTimes = borrowTimes;
    }
    public int getOrderTimes() {
        return this.orderTimes;
    }
    
    public void setOrderTimes(int orderTimes) {
        this.orderTimes = orderTimes;
    }
    public Set getTags() {
        return this.tags;
    }
    
    public void setTags(Set tags) {
        this.tags = tags;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }
    public Set getCopies() {
        return this.copies;
    }
    
    public void setCopies(Set copies) {
        this.copies = copies;
    }
    public Set getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set authors) {
        this.authors = authors;
    }




}


