package sample.entity;
// Generated Nov 22, 2014 5:12:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Borrow generated by hbm2java
 */
public class Borrow  implements java.io.Serializable {


     private int borrowId;
     private Account accountByBorrower;
     private Account accountByAccepter;
     private Copy copy;
     private Date borrowDate;
     private Date deadline;

    public Borrow() {
    }

    public Borrow(int borrowId, Account accountByBorrower, Account accountByAccepter, Copy copy, Date borrowDate, Date deadline) {
       this.borrowId = borrowId;
       this.accountByBorrower = accountByBorrower;
       this.accountByAccepter = accountByAccepter;
       this.copy = copy;
       this.borrowDate = borrowDate;
       this.deadline = deadline;
    }
   
    public int getBorrowId() {
        return this.borrowId;
    }
    
    public void setBorrowId(int borrowId) {
        this.borrowId = borrowId;
    }
    public Account getAccountByBorrower() {
        return this.accountByBorrower;
    }
    
    public void setAccountByBorrower(Account accountByBorrower) {
        this.accountByBorrower = accountByBorrower;
    }
    public Account getAccountByAccepter() {
        return this.accountByAccepter;
    }
    
    public void setAccountByAccepter(Account accountByAccepter) {
        this.accountByAccepter = accountByAccepter;
    }
    public Copy getCopy() {
        return this.copy;
    }
    
    public void setCopy(Copy copy) {
        this.copy = copy;
    }
    public Date getBorrowDate() {
        return this.borrowDate;
    }
    
    public void setBorrowDate(Date borrowDate) {
        this.borrowDate = borrowDate;
    }
    public Date getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }




}


