package sample.entity;
// Generated Nov 22, 2014 5:12:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Copy generated by hbm2java
 */
public class Copy  implements java.io.Serializable {


     private int barcode;
     private Book book;
     private Magazine magazine;
     private boolean isAvailable;
     private boolean isAble;
     private Set borrows = new HashSet(0);

    public Copy() {
    }

	
    public Copy(int barcode, boolean isAvailable, boolean isAble) {
        this.barcode = barcode;
        this.isAvailable = isAvailable;
        this.isAble = isAble;
    }
    public Copy(int barcode, Book book, Magazine magazine, boolean isAvailable, boolean isAble, Set borrows) {
       this.barcode = barcode;
       this.book = book;
       this.magazine = magazine;
       this.isAvailable = isAvailable;
       this.isAble = isAble;
       this.borrows = borrows;
    }
   
    public int getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(int barcode) {
        this.barcode = barcode;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public Magazine getMagazine() {
        return this.magazine;
    }
    
    public void setMagazine(Magazine magazine) {
        this.magazine = magazine;
    }
    public boolean isIsAvailable() {
        return this.isAvailable;
    }
    
    public void setIsAvailable(boolean isAvailable) {
        this.isAvailable = isAvailable;
    }
    public boolean isIsAble() {
        return this.isAble;
    }
    
    public void setIsAble(boolean isAble) {
        this.isAble = isAble;
    }
    public Set getBorrows() {
        return this.borrows;
    }
    
    public void setBorrows(Set borrows) {
        this.borrows = borrows;
    }




}


