package sample.entity;
// Generated Nov 22, 2014 5:12:09 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Magazine generated by hbm2java
 */
public class Magazine  implements java.io.Serializable {


     private Serializable issn;
     private Publisher publisher;
     private Serializable image;
     private Serializable about;
     private double price;
     private int borrowTime;
     private Boolean isAble;
     private int numOfCopies;
     private int copiesAvailable;
     private int borrowTimes;
     private int orderTimes;
     private Set copies = new HashSet(0);

    public Magazine() {
    }

	
    public Magazine(Serializable issn, Publisher publisher, Serializable image, Serializable about, double price, int borrowTime, int numOfCopies, int copiesAvailable, int borrowTimes, int orderTimes) {
        this.issn = issn;
        this.publisher = publisher;
        this.image = image;
        this.about = about;
        this.price = price;
        this.borrowTime = borrowTime;
        this.numOfCopies = numOfCopies;
        this.copiesAvailable = copiesAvailable;
        this.borrowTimes = borrowTimes;
        this.orderTimes = orderTimes;
    }
    public Magazine(Serializable issn, Publisher publisher, Serializable image, Serializable about, double price, int borrowTime, Boolean isAble, int numOfCopies, int copiesAvailable, int borrowTimes, int orderTimes, Set copies) {
       this.issn = issn;
       this.publisher = publisher;
       this.image = image;
       this.about = about;
       this.price = price;
       this.borrowTime = borrowTime;
       this.isAble = isAble;
       this.numOfCopies = numOfCopies;
       this.copiesAvailable = copiesAvailable;
       this.borrowTimes = borrowTimes;
       this.orderTimes = orderTimes;
       this.copies = copies;
    }
   
    public Serializable getIssn() {
        return this.issn;
    }
    
    public void setIssn(Serializable issn) {
        this.issn = issn;
    }
    public Publisher getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }
    public Serializable getImage() {
        return this.image;
    }
    
    public void setImage(Serializable image) {
        this.image = image;
    }
    public Serializable getAbout() {
        return this.about;
    }
    
    public void setAbout(Serializable about) {
        this.about = about;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getBorrowTime() {
        return this.borrowTime;
    }
    
    public void setBorrowTime(int borrowTime) {
        this.borrowTime = borrowTime;
    }
    public Boolean getIsAble() {
        return this.isAble;
    }
    
    public void setIsAble(Boolean isAble) {
        this.isAble = isAble;
    }
    public int getNumOfCopies() {
        return this.numOfCopies;
    }
    
    public void setNumOfCopies(int numOfCopies) {
        this.numOfCopies = numOfCopies;
    }
    public int getCopiesAvailable() {
        return this.copiesAvailable;
    }
    
    public void setCopiesAvailable(int copiesAvailable) {
        this.copiesAvailable = copiesAvailable;
    }
    public int getBorrowTimes() {
        return this.borrowTimes;
    }
    
    public void setBorrowTimes(int borrowTimes) {
        this.borrowTimes = borrowTimes;
    }
    public int getOrderTimes() {
        return this.orderTimes;
    }
    
    public void setOrderTimes(int orderTimes) {
        this.orderTimes = orderTimes;
    }
    public Set getCopies() {
        return this.copies;
    }
    
    public void setCopies(Set copies) {
        this.copies = copies;
    }




}


