package sample.entity;
// Generated Nov 22, 2014 5:12:09 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private byte[] isbn;
     private Book book;
     private Account account;
     private Date orderDate;
     private Date requireDate;
     private Date returnDate;
     private Serializable status;

    public Order() {
    }

	
    public Order(byte[] isbn, Book book, Account account, Date orderDate, Serializable status) {
        this.isbn = isbn;
        this.book = book;
        this.account = account;
        this.orderDate = orderDate;
        this.status = status;
    }
    public Order(byte[] isbn, Book book, Account account, Date orderDate, Date requireDate, Date returnDate, Serializable status) {
       this.isbn = isbn;
       this.book = book;
       this.account = account;
       this.orderDate = orderDate;
       this.requireDate = requireDate;
       this.returnDate = returnDate;
       this.status = status;
    }
   
    public byte[] getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(byte[] isbn) {
        this.isbn = isbn;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Date getRequireDate() {
        return this.requireDate;
    }
    
    public void setRequireDate(Date requireDate) {
        this.requireDate = requireDate;
    }
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }
    public Serializable getStatus() {
        return this.status;
    }
    
    public void setStatus(Serializable status) {
        this.status = status;
    }




}


