package sample.entity;
// Generated Nov 22, 2014 5:12:09 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Publisher generated by hbm2java
 */
public class Publisher  implements java.io.Serializable {


     private int publisherId;
     private Serializable companyName;
     private Serializable address;
     private Serializable phone;
     private Serializable email;
     private Serializable logo;
     private Set magazines = new HashSet(0);
     private Set books = new HashSet(0);

    public Publisher() {
    }

	
    public Publisher(int publisherId, Serializable companyName, Serializable address, Serializable phone, Serializable email, Serializable logo) {
        this.publisherId = publisherId;
        this.companyName = companyName;
        this.address = address;
        this.phone = phone;
        this.email = email;
        this.logo = logo;
    }
    public Publisher(int publisherId, Serializable companyName, Serializable address, Serializable phone, Serializable email, Serializable logo, Set magazines, Set books) {
       this.publisherId = publisherId;
       this.companyName = companyName;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.logo = logo;
       this.magazines = magazines;
       this.books = books;
    }
   
    public int getPublisherId() {
        return this.publisherId;
    }
    
    public void setPublisherId(int publisherId) {
        this.publisherId = publisherId;
    }
    public Serializable getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(Serializable companyName) {
        this.companyName = companyName;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public Serializable getPhone() {
        return this.phone;
    }
    
    public void setPhone(Serializable phone) {
        this.phone = phone;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getLogo() {
        return this.logo;
    }
    
    public void setLogo(Serializable logo) {
        this.logo = logo;
    }
    public Set getMagazines() {
        return this.magazines;
    }
    
    public void setMagazines(Set magazines) {
        this.magazines = magazines;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


