package sample.entity;
// Generated Nov 22, 2014 5:12:09 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private Serializable tagName;
     private Set books = new HashSet(0);

    public Tag() {
    }

	
    public Tag(Serializable tagName) {
        this.tagName = tagName;
    }
    public Tag(Serializable tagName, Set books) {
       this.tagName = tagName;
       this.books = books;
    }
   
    public Serializable getTagName() {
        return this.tagName;
    }
    
    public void setTagName(Serializable tagName) {
        this.tagName = tagName;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


